Update patch set 10
Patch Set 10: Code-Review-1

Jonathan,

We have made the oom changes and tested with OOM locally, see linked Gerrit reviews that are on the same topic :

https://gerrit.onap.org/r/c/oom/+/103790
https://gerrit.onap.org/r/c/aaf/sms/+/103788


We can make the changes to the local repo helm charts (we just use an init container to chmod the NFS mount, which is the recommended k8s way) but what are their purpose ? it looks like a local way to deploy with helm and it will duplicate code and effort.

I tested your changes  (patchset 10) on my local oom setup but
the bootstrap script executes but fails at several places :

 Cassandra responded
 cassandra responsive
 /opt/app/aaf/cass_init/cmd.sh: line 100: /usr/bin/cqlsh: No such file or directory
 /opt/app/aaf/cass_init/cmd.sh: line 104: /usr/bin/cqlsh: No such file or directory
 install
 Initializing Cassandra DB
 Docker Installed Basic Cassandra on aaf.cass.  Executing the following 
 NOTE: This creator provided is only a Single Instance. For more complex Cassandra, create  independently

 cd /opt/app/aaf/cass_init
 cqlsh -f keyspace.cql
 /opt/app/aaf/cass_init/cmd.sh: line 113: /usr/bin/cqlsh: No such file or directory
 keyspace installed
 cqlsh -f init.cql
 /opt/app/aaf/cass_init/cmd.sh: line 116: /usr/bin/cqlsh: No such file or directory
 data initialized

 The following will give you a temporary identity with which to start working, or emergency
 cqlsh -f temp_identity.cql
 initialized
 prep data for bootstrapping
 prep data
 push data to cassandra
 Tue Mar 24 10:24:08 CET 2020
 /opt/app/aaf/cass_init
 You are about to REPLACE the data in the DOCKER DB for the following tables:
 artifact config cred ns perm role user_role
 If you are VERY sure, type "YES": artifact
 restore.sh: line 39: /usr/bin/cqlsh: No such file or directory
 config
 restore.sh: line 47: /usr/bin/cqlsh: No such file or directory
 cred
 restore.sh: line 39: /usr/bin/cqlsh: No such file or directory
 ns
 restore.sh: line 39: /usr/bin/cqlsh: No such file or directory
 perm
 restore.sh: line 47: /usr/bin/cqlsh: No such file or directory
 role
 user_role
 restore.sh: line 39: /usr/bin/cqlsh: No such file or directory
 restore.sh: line 47: /usr/bin/cqlsh: No such file or directory
 #### Running artifact.dat Feed ####
 com.datastax.driver.core.exceptions.InvalidQueryException: Keyspace authz does not exist
	at   com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:49)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
	at  com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java: 293)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:58)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:39)
	at org.onap.aaf.auth.batch.helpers.CQLBatch.execute(CQLBatch.java:75)
	at org.onap.aaf.auth.batch.helpers.CQLBatch.execute(CQLBatch.java:99)
	at org.onap.aaf.auth.batch.helpers.CQLBatchLoop.flush(CQLBatchLoop.java:98)
	at org.onap.aaf.auth.batch.update.Upload.run(Upload.java:130)

this is why we updated to

/opt/cassandra/bin/cqlsh

which is where we find the cqlsh tool in the container

Patch-set: 10
Label: Code-Review=-1